--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/Spooky
projects:
  Spooky:
    path: ""
    libs:
      - src: thebigsmilexd/skinapi/skinapi
        version: ^0.2.0
...
